### ISSUE TITLE
關於python程式設計入門P.7-33

### ISSUE THREAD

**Issue by howard2002tw** [letylin/pyptbook#9]
關於pandans在資料讀取上好像有技術上的問題:
(1)會產生is_list_like is not defined
(2)目前好像無法抓取超過四

**Comment by Arzeht** [comment]
您好，因2311股票已經合併，故抓不到該股票以至於出錯
近期會更新線上的程式碼，再請您重新下載，謝謝您的發問！

by 本書助理

**Comment by Arzeht** [comment]
已經更新程式碼了，請您在嘗試看看

您的錯誤碼我看不太明白，
您方便的話將完整的程式碼跟錯誤碼寄到下面的信箱
fintech@gm.kuas.edu.tw

以便做問題的釐清
謝謝您的回覆！

**Comment by howard2002tw** [comment]
P.7-33

執行程式:

import fix_yahoo_finance as yf
import pandas as pd
import datetime
import time
starttime = time.clock()

yf.pdr_override() # <== that's all it takes :-)
start = datetime.datetime(2016,1,1)
end = datetime.datetime(2018,3,1)
stockid=('2303', '2330', '3008', '2498', '2002', '2409', '2357', '2317')
writer=pd.ExcelWriter('./file/stocprice_revised.xlsx')
print(type(stockid))
for i in range(0,len(stockid)):
    sid=stockid[i]+'.tw'
    df = pdr.get_data_yahoo(sid, start, end)
    df.to_excel(writer,stockid[i])
writer.save()
endtime = time.clock()
print(' 程式執行時間 = %d %s' %(round(endtime - starttime), ' 秒’))

結果:

/Users/yen-kuangchen/PycharmProjects/FinTech/venv/bin/python /Users/yen-kuangchen/PycharmProjects/FinTech/Ch7.py
Traceback (most recent call last):
  File "/Users/yen-kuangchen/PycharmProjects/FinTech/Ch7.py", line 40, in <module>
    from pandas_datareader import data as pdr
  File "/Users/yen-kuangchen/PycharmProjects/FinTech/venv/lib/python3.6/site-packages/pandas_datareader/__init__.py", line 2, in <module>
    from .data import (DataReader, Options, get_components_yahoo,
  File "/Users/yen-kuangchen/PycharmProjects/FinTech/venv/lib/python3.6/site-packages/pandas_datareader/data.py", line 14, in <module>
    from pandas_datareader.fred import FredReader
  File "/Users/yen-kuangchen/PycharmProjects/FinTech/venv/lib/python3.6/site-packages/pandas_datareader/fred.py", line 1, in <module>
    from pandas.core.common import is_list_like
ImportError: cannot import name 'is_list_like'




Yen-Kuang Chen <howard2002tw@hotmail.com<mailto:howard2002tw@hotmail.com>> 於 2018年9月11日 下午1:21 寫道：

你好,好像不是股票的問題,因為我有修改號碼
以下是我遇到的問題
(1)is_list_like
<3DF25388-A0E1-4608-BF10-946E3BA633B1.png>

(2)是超過四筆資料
＠四筆資料的時候
<螢幕快照 2018-09-09 下午5.38.45.png>

＠第五筆資料的時候
<螢幕快照 2018-09-09 下午5.42.19.png>
Arzeht <notifications@github.com<mailto:notifications@github.com>> 於 2018年9月11日 下午1:02 寫道：


您好，因2311股票已經合併，故抓不到該股票以至於出錯
近期會更新線上的程式碼，再請您重新下載，謝謝您的發問！

by 本書助理

**Comment by Arzeht** [comment]
![image](https://user-images.githubusercontent.com/40318843/45362550-b4d9d080-b607-11e8-8b84-595207036dc5.png)
請您找到此檔案

您的路經應該是
C:/Users/yen-kuangchen/PycharmProjects/FinTech/venv/lib/python3.6/site-packages/pandas_datareader/fred.py

如圖第一行
並將from pandas.core.common import is_list_like
改成from pandas.api.common import is_list_like
試試看

參考自 https://www.cnblogs.com/NewsunLs/p/9216785.html

**Comment by Arzeht** [comment]
應該是套件版本上的問題沒錯
因為我的電腦用core跑沒問題

**Comment by letylin** [comment]
github的討論參與者您好！
您在這邊的留言我們比較難在第一時間收到資訊，
所以在這邊邀請您加入我們的LINE@ 1對1聊天群組，
您可以在LINE上討論有關於書中的問題，
讓我們能快速知道您的疑問並與您討論！

LINE@ID：@iex5378o
~~~使用手機者點選以下網址或使用電腦者掃描以下QRCode立即加入群組~~~
https://line.me/R/ti/p/%40iex5378o
 
![line](https://user-images.githubusercontent.com/20430722/46133100-4be29180-c272-11e8-93e4-cba599cc4ccc.jpg)
